C#/Fiap.Revisao/Fiap.Revisao/Models/Empresa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Revisao.Models
{
    public class Empresa
    {
        public int EmpresaId { get; set; }

        [Required]
        [Display(Name ="CNPJ")]
        public int Cnpj { get; set; }

        [Required]
        [StringLength(200, ErrorMessage = "Máximo de 200 caracteres")]
        [Display(Name = "Razão Social")]
        public string RazaoSocial { get; set; }

        //Relacionamento
        public List<Funcionario> Funcionarios { get; set; }
    }
}

C#/Fiap.Revisao/Fiap.Revisao/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Revisao.Models
{
    public class Funcionario
    {
        public int FuncionarioId { get; set; }

        [Required]
        [StringLength(200, ErrorMessage = "Possui mais de 200 caracteres")]
        public string Nome { get; set; }

        [Required]
        public decimal Salario { get; set; }

        [Required]
        [Display(Name ="Data de Admissão")]
        public DateTime DataAdmissao { get; set; }

        //Relacionamento
        public Empresa Empresa { get; set; }

        [Required]
        public int EmpresaId { get; set; }
    }
}

C#/Fiap.Revisao/Fiap.Revisao/Controllers/EmpresaController.cs
using Fiap.Revisao.Models;
using Fiap.Revisao.Units;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Revisao.Controllers
{
    public class EmpresaController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        //Cadastrar
        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                _unit.EmpresaRepository.Cadastrar(empresa);
                _unit.Salvar();
                TempData["msg"] = "Empresa Cadastrada com Sucesso!";
                return RedirectToAction("Cadastrar");
            }
            else
            {
                return View(empresa);
            }
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

C#/Fiap.Revisao/Fiap.Revisao/Controllers/FuncionarioController.cs
using Fiap.Revisao.Models;
using Fiap.Revisao.Units;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Revisao.Controllers
{
    public class FuncionarioController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        //Cadastrar
        [HttpGet]
        public ActionResult Cadastrar()
        {
            var lista = _unit.EmpresaRepository.Listar();
            ViewBag.empresas = new SelectList(lista, "EmpresaId", "RazaoSocial");
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                _unit.FuncionarioRepository.Cadastrar(funcionario);
                _unit.Salvar();
                TempData["msg"] = "Empresa Cadastrada com Sucesso!";
                return RedirectToAction("Cadastrar");
            }
            else
            {
                var lista = _unit.EmpresaRepository.Listar();
                ViewBag.empresas = new SelectList(lista, "EmpresaId", "RazaoSocial");
                return View(funcionario);
            }
        }

        //Listar
        [HttpGet]
        public ActionResult Listar()
        {
           return View(_unit.FuncionarioRepository.Listar());
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

C#/Fiap.Revisao/Fiap.Revisao/Views/Funcionario/Cadastrar.cshtml
@model Fiap.Revisao.Models.Funcionario
@{
    ViewBag.Title = "Cadastrar";
}

@if(TempData["msg"] != null)
{
    <div class="alert alert-success">@TempData["msg"]</div>
}
<h2>Cadastrar</h2>
@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(f => f.Nome)
        @Html.TextBoxFor(f => f.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(f => f.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(f => f.Salario)
        @Html.TextBoxFor(f => f.Salario, new { @class = "form-control" })
        @Html.ValidationMessageFor(f => f.Salario)
    </div>
    <div class="form-group">
        @Html.LabelFor(f => f.DataAdmissao)
        @Html.TextBoxFor(f => f.DataAdmissao, new { @class = "form-control" })
        @Html.ValidationMessageFor(f => f.DataAdmissao)
    </div>
    <div class="form-group">
        @Html.LabelFor(f => f.Empresa)
        @Html.DropDownListFor(f => f.EmpresaId, ViewBag.empresas as SelectList, "Selecione", new { @class="form-control" })
        @Html.ValidationMessageFor(f => f.EmpresaId)
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary"/>
}

C#/Fiap.Revisao/Fiap.Revisao/Views/Funcionario/Listar.cshtml
@model List<Fiap.Revisao.Models.Funcionario>
@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>
<table class="table table-striped">
    <tr>
        <th>Nome</th>
        <th>Salario</th>
        <th>Data de Admissao</th>
        <th>Empresa</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Salario</td>
            <td>@item.DataAdmissao.ToShortDateString()</td>
            <td>@item.Empresa.RazaoSocial</td>
        </tr>
    }
</table> 

C#/Fiap.Revisao/Fiap.Revisao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Revisao PS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastrar Empresa", "Cadastrar", "Empresa")</li>
                    <li>@Html.ActionLink("Cadastrar Funcionario", "Cadastrar", "Funcionario")</li>
                    <li>@Html.ActionLink("Funcionarios", "Listar","Funcionario")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Copyright RM76093</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>