C#/Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Models/Campeonato.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo04.MVC.Models
{
    public class Campeonato
    {
        public int CampeonatoId { get; set; }
        public string Nome { get; set; }
        public decimal Premiacao { get; set; }
        //Relacionamentos
        public List<Time> Times { get; set; }
    }
}

C#/Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Models/Jogador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo04.MVC.Models
{
    public class Jogador
    {
        public int JogadorId { get; set; }

        [Required]
        [StringLength(200, ErrorMessage = "O Máximo de Caractéres é de 200")]
        public string Nome { get; set; }

        [Required]
        [DataType(DataType.DateTime, ErrorMessage = "Data Inválida")]
        public DateTime DataNascimento { get; set; }

        //Relacionamentos
        public Time Time { get; set; }

        [Required]
        public int TimeId { get; set; }
    }
}

C#/Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Models/Tecnico.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo04.MVC.Models
{
    public class Tecnico
    {
        public int TecnicoId { get; set; }
        public string Nome { get; set; }
        public int NumeroTitulos { get; set; }
    }
}

C#/Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Models/Time.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo04.MVC.Models
{
    public class Time
    {
        public int TimeId { get; set; }

        [Required]
        [StringLength(200, ErrorMessage = "Máximo de 200 caractéres")]
        public string Nome { get; set; }
        [Display(Name ="Data de Fundação")]
        public DateTime DataFundacao { get; set; }

        //Relacionamentos
        public Tecnico Tecnico { get; set; }
        public int TecnicoId { get; set; }

        public List<Jogador> Jogadores { get; set; }

        public List<Campeonato> Campeonatos { get; set; }
    }
}

C#/Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Controllers/JogadorController.cs
using Fiap.Exemplo04.MVC.Models;
using Fiap.Exemplo04.MVC.Persistencia;
using Fiap.Exemplo04.MVC.Units;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo04.MVC.Controllers
{
    public class JogadorController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult Listar()
        {
            return View(_unit.JogadorRepository.Listar());
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            //Buscar todos os times cadastrados
            var lista = _unit.TimeRepository.Listar();
            //Passa os valores para o select da tela
            ViewBag.times = new SelectList(lista, "TimeId", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Jogador jogador)
        {
            if (ModelState.IsValid)
            {
                _unit.JogadorRepository.Cadastrar(jogador);
                _unit.Save();
                TempData["msg"] = "Jogador Cadastrado!";
                return RedirectToAction("Cadastrar");
            }else
            {
                //Buscar todos os times cadastrados
                var lista = _unit.TimeRepository.Listar();
                //Passa os valores para o select da tela
                ViewBag.times = new SelectList(lista, "TimeId", "Nome");                
				return View(jogador);
            }
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

C#/Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Controllers/TimeController.cs
using Fiap.Exemplo04.MVC.Models;
using Fiap.Exemplo04.MVC.Persistencia;
using Fiap.Exemplo04.MVC.Units;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo04.MVC.Controllers
{
    public class TimeController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult Listar()
        {            
            //Busca os times com os tecnicos também
            return View(_unit.TimeRepository.Listar());
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Cadastrar(Time time)
        {
            if (ModelState.IsValid)
            { 
                _unit.TimeRepository.Cadastrar(time);
                _unit.Save();
                TempData["msg"] = "Cadastrado!";
                return RedirectToAction("Cadastrar");
            }
            else
            {
                return View(time);
            }
        }

        //Libera a conexão
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }

    }
}

C#/Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Futebol", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastro Jogador","Cadastrar","Jogador")</li>
                    <li>@Html.ActionLink("Cadastro Time","Cadastrar","Time")</li>
                    <li>@Html.ActionLink("Jogadores","Listar","Jogador")</li>
                    <li>@Html.ActionLink("Times","Listar","Time")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</body>
</html>

C#/Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Views/Time/Cadastrar.cshtml
@model Fiap.Exemplo04.MVC.Models.Time
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Time</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">@TempData["msg"]</div>
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <div class="form-group">
        @Html.LabelFor(t => t.Nome)
        @Html.TextBoxFor(t => t.Nome, new { @class = "form-control"})
        @Html.ValidationMessageFor(t => t.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(t => t.DataFundacao)
        @Html.TextBoxFor(t => t.DataFundacao, new { @class = "form-control"})
        @Html.ValidationMessageFor(t => t.DataFundacao)
    </div>
    <fieldset>
        <legend>Técnico</legend>
        <div class="form-group">
            @Html.LabelFor(t => t.Tecnico.Nome)
            @Html.TextBoxFor(t => t.Tecnico.Nome, new { @class = "form-control"})
            @Html.ValidationMessageFor(t => t.Tecnico.Nome)
        </div>
        <div class="form-group">
            @Html.LabelFor(t => t.Tecnico.NumeroTitulos)
            @Html.TextBoxFor(t => t.Tecnico.NumeroTitulos, new { @class = "form-control"})
            @Html.ValidationMessageFor(t => t.Tecnico.NumeroTitulos)
        </div>
    </fieldset>
    <input type="submit" value="Salvar" class="btn btn-primary" />
}

C#/Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Views/Time/Listar.cshtml
@model List<Fiap.Exemplo04.MVC.Models.Time>
@{
    ViewBag.Title = "Listar";
}

<h2>Times</h2>

<table class="table table-striped">
    <tr>
        <th>Nome</th>
        <th>Data Fundação</th>
        <th>Técnico</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.DataFundacao.ToShortDateString()</td>
            <td>@item.Tecnico.Nome</td>
        </tr>
    }
</table>