C#/Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Models/Fruta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo03.MVC.Models
{
    public class Fruta
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100,MinimumLength =3)]
        public string Nome { get; set; }

        public float Calorias { get; set; }

        [Display(Name = "Orgânico")]
        public bool Organico { get; set; }

        public bool Semente { get; set; }

        [Required]
        public DateTime DataCadastro { get; set; }
    }
}

C#/Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Models/Produtor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo03.MVC.Models
{
    public class Produtor
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 3)]
        public string Nome { get; set; }

        public bool Certificado { get; set; }

        [Required]
        public DateTime DataCadastro { get; set; }

        public decimal Limite { get; set; }
    }
}

C#/Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Controllers/FrutaController.cs
using Fiap.Exemplo03.MVC.Models;
using Fiap.Exemplo03.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo03.MVC.Controllers
{
    public class FrutaController : Controller
    {
        private SacolaoContext _context = new SacolaoContext();

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Fruta fruta)
        {
            fruta.DataCadastro = DateTime.Now;
            _context.Frutas.Add(fruta);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado!";
            //Para não cadastrar novamente no F5
            return RedirectToAction("Cadastrar");
        }

        [HttpGet]
        public ActionResult Listar()
        {
            return View(_context.Frutas.ToList());
        }
    }
}

C#/Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo03.MVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

C#/Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Controllers/ProdutorController.cs
using Fiap.Exemplo03.MVC.Models;
using Fiap.Exemplo03.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo03.MVC.Controllers
{
    public class ProdutorController : Controller
    {
        private SacolaoContext _context = new SacolaoContext();
        // GET: Produtor
        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Produtor produtor)
        {
            produtor.DataCadastro = DateTime.Now;
            //"Instancia um novo produtor no banco"
            _context.Produtores.Add(produtor);
            //Salva no banco
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado!";
            //Para nao cadastrar novamente no F5
            return RedirectToAction("Cadastrar");
        }
        [HttpGet]
        public ActionResult Listar()
        {
            return View(_context.Produtores.ToList());
        }
    }
}

C#/Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Views/Fruta/Cadastrar.cshtml
@model Fiap.Exemplo03.MVC.Models.Fruta
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(f => f.Nome)
        @Html.TextBoxFor(f => f.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(f => f.Calorias)
        @Html.TextBoxFor(f => f.Calorias, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(f => f.Organico)
        @Html.LabelFor(f => f.Organico)
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(f => f.Semente)
        @Html.LabelFor(f => f.Semente)
    </div>
    <input type="submit" value="Salvar" class="btn btn-primary" />
}

C#/Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Views/Fruta/Listar.cshtml
@model List<Fiap.Exemplo03.MVC.Models.Fruta>
@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>
<table class="table">
    <tr>
        <th>Nome</th>
        <th>Calorias</th>
        <th>Orgânico</th>
        <th>Semente</th>
        <th>Data de Cadastro</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Calorias</td>
            <td>@(item.Organico ? "Sim" : "Não")</td>
            <td>@(item.Semente ? "Sim" : "Não")</td>
            <td>@item.DataCadastro.ToShortDateString()</td>
        </tr>
    }
</table>

C#/Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sacolão das Frutas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu de Frutas <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro de Fruta", "Cadastrar", "Fruta")</li> 
                            <li>@Html.ActionLink("Lista de Fruta", "Listar", "Fruta")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu de Produtores <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro de Produtor", "Cadastrar", "Produtor")</li> 
                            <li>@Html.ActionLink("Lista de Produtores", "Listar", "Produtor")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>