C#/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Models/Vaga.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo02.MVC.Models
{
    public class Vaga
    {
        public string Cargo { get; set; }

        [Display(Name ="Descrição")]
        public string Descricao { get; set; }

        [Display(Name = "Salário")]
        public decimal Salario { get; set; }

        [Display(Name = "VR")]
        public bool ValeRefeicao { get; set; }

        [Display(Name = "Nível")]
        public string Nivel { get; set; }
    }
}

C#/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Controllers/VagaController.cs
using Fiap.Exemplo02.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo02.MVC.Controllers
{
    public class VagaController : Controller
    {
        //Simular o banco de dados....
        private static List<Vaga> _banco = new List<Vaga>();
       
        [HttpGet]
        public ActionResult Cadastrar()
        {
            PopulaComboNiveis();

            return View();
        }

        private void PopulaComboNiveis()
        {
            //Valores para preencher o select
            List<string> niveis = new List<string>();
            niveis.Add("Junior");
            niveis.Add("Pleno");
            niveis.Add("Sênior");
            ViewBag.opcoes = new SelectList(niveis);
        }

        [HttpPost]
        public ActionResult Cadastrar(Vaga vaga)
        {
            //cadastra no banco de dados
            _banco.Add(vaga);
            //Mensagem de sucesso para a view
            TempData["msg"] = "Vaga registrada!";
            PopulaComboNiveis();
            return View();
        }

        [HttpGet]
        public ActionResult Listar()
        {
            //Retorna a lista de vagas para a view
            return View(_banco);
        }
    }
}

C#/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP Jobs", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vaga <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro", "Cadastrar", "Vaga")</li>
                            <li>@Html.ActionLink("Listagem", "Listar", "Vaga")</li>        
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts",false)
</body>
</html>